apiRules:

- exclude:
      uidRegex: ^System\.Object
      type: Type

- exclude:
      uidRegex: ^PureHDF\.SourceGenerator
      type: Type

- exclude:
      uidRegex: ^PureHDF\.VOL\.HsdsClientGenerator
      type: Type